### ISSUE TITLE
User Story: Demo

### ISSUE THREAD

**Issue by the-alex** [hrnyc-targaryen/thesis#12]
- [ ] User is on dashboard and selects a campaign, taking them to the campaign details page. Related: #4
- [ ] User clicks send on campaign details page. Related: #4, #5
- [ ] An API call to SendGrid is made by the backend. Related: #6, #7
